/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiTripSearchMetadata
 */
public class ApiTripSearchMetadataTest {
    private final ApiTripSearchMetadata model = new ApiTripSearchMetadata();

    /**
     * Model tests for ApiTripSearchMetadata
     */
    @Test
    public void testApiTripSearchMetadata() {
        // TODO: test ApiTripSearchMetadata
    }

    /**
     * Test the property 'searchWindowUsed'
     */
    @Test
    public void searchWindowUsedTest() {
        // TODO: test searchWindowUsed
    }

    /**
     * Test the property 'nextDateTime'
     */
    @Test
    public void nextDateTimeTest() {
        // TODO: test nextDateTime
    }

    /**
     * Test the property 'prevDateTime'
     */
    @Test
    public void prevDateTimeTest() {
        // TODO: test prevDateTime
    }

}
