/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BikeStreetCategory
 */
public class BikeStreetCategoryTest {
    /**
     * Model tests for BikeStreetCategory
     */
    @Test
    public void testBikeStreetCategory() {
        // TODO: test BikeStreetCategory
    }

}
