/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.TicketingLocation;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Place
 */
public class PlaceTest {
    private final Place model = new Place();

    /**
     * Model tests for Place
     */
    @Test
    public void testPlace() {
        // TODO: test Place
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ticketingLocation'
     */
    @Test
    public void ticketingLocationTest() {
        // TODO: test ticketingLocation
    }

    /**
     * Test the property 'stopId'
     */
    @Test
    public void stopIdTest() {
        // TODO: test stopId
    }

    /**
     * Test the property 'stopCode'
     */
    @Test
    public void stopCodeTest() {
        // TODO: test stopCode
    }

    /**
     * Test the property 'platformCode'
     */
    @Test
    public void platformCodeTest() {
        // TODO: test platformCode
    }

    /**
     * Test the property 'lon'
     */
    @Test
    public void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'arrival'
     */
    @Test
    public void arrivalTest() {
        // TODO: test arrival
    }

    /**
     * Test the property 'departure'
     */
    @Test
    public void departureTest() {
        // TODO: test departure
    }

    /**
     * Test the property 'orig'
     */
    @Test
    public void origTest() {
        // TODO: test orig
    }

    /**
     * Test the property 'stopIndex'
     */
    @Test
    public void stopIndexTest() {
        // TODO: test stopIndex
    }

    /**
     * Test the property 'stopSequence'
     */
    @Test
    public void stopSequenceTest() {
        // TODO: test stopSequence
    }

}
