/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlannerError
 */
public class PlannerErrorTest {
    private final PlannerError model = new PlannerError();

    /**
     * Model tests for PlannerError
     */
    @Test
    public void testPlannerError() {
        // TODO: test PlannerError
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'missing'
     */
    @Test
    public void missingTest() {
        // TODO: test missing
    }

    /**
     * Test the property 'noPath'
     */
    @Test
    public void noPathTest() {
        // TODO: test noPath
    }

    /**
     * Test the property 'msgFromMessage'
     */
    @Test
    public void msgFromMessageTest() {
        // TODO: test msgFromMessage
    }

}
