/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TicketingPeriod
 */
public class TicketingPeriodTest {
    private final TicketingPeriod model = new TicketingPeriod();

    /**
     * Model tests for TicketingPeriod
     */
    @Test
    public void testTicketingPeriod() {
        // TODO: test TicketingPeriod
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

    /**
     * Test the property 'opens'
     */
    @Test
    public void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'closes'
     */
    @Test
    public void closesTest() {
        // TODO: test closes
    }

    /**
     * Test the property 'opensSeconds'
     */
    @Test
    public void opensSecondsTest() {
        // TODO: test opensSeconds
    }

    /**
     * Test the property 'closesSeconds'
     */
    @Test
    public void closesSecondsTest() {
        // TODO: test closesSeconds
    }

}
