/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TranslatedString
 */
public class TranslatedStringTest {
    private final TranslatedString model = new TranslatedString();

    /**
     * Model tests for TranslatedString
     */
    @Test
    public void testTranslatedString() {
        // TODO: test TranslatedString
    }

    /**
     * Test the property 'translations'
     */
    @Test
    public void translationsTest() {
        // TODO: test translations
    }

    /**
     * Test the property 'someTranslation'
     */
    @Test
    public void someTranslationTest() {
        // TODO: test someTranslation
    }

}
