/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransitTripStopTime
 */
public class TransitTripStopTimeTest {
    private final TransitTripStopTime model = new TransitTripStopTime();

    /**
     * Model tests for TransitTripStopTime
     */
    @Test
    public void testTransitTripStopTime() {
        // TODO: test TransitTripStopTime
    }

    /**
     * Test the property 'stopId'
     */
    @Test
    public void stopIdTest() {
        // TODO: test stopId
    }

    /**
     * Test the property 'stopHeadsign'
     */
    @Test
    public void stopHeadsignTest() {
        // TODO: test stopHeadsign
    }

    /**
     * Test the property 'arrivalTime'
     */
    @Test
    public void arrivalTimeTest() {
        // TODO: test arrivalTime
    }

    /**
     * Test the property 'departureTime'
     */
    @Test
    public void departureTimeTest() {
        // TODO: test departureTime
    }

    /**
     * Test the property 'predictedArrivalTime'
     */
    @Test
    public void predictedArrivalTimeTest() {
        // TODO: test predictedArrivalTime
    }

    /**
     * Test the property 'predictedDepartureTime'
     */
    @Test
    public void predictedDepartureTimeTest() {
        // TODO: test predictedDepartureTime
    }

    /**
     * Test the property 'uncertain'
     */
    @Test
    public void uncertainTest() {
        // TODO: test uncertain
    }

    /**
     * Test the property 'requiresBooking'
     */
    @Test
    public void requiresBookingTest() {
        // TODO: test requiresBooking
    }

    /**
     * Test the property 'stopSequence'
     */
    @Test
    public void stopSequenceTest() {
        // TODO: test stopSequence
    }

    /**
     * Test the property 'shapeDistTraveled'
     */
    @Test
    public void shapeDistTraveledTest() {
        // TODO: test shapeDistTraveled
    }

}
