/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransitTrip
 */
public class TransitTripTest {
    private final TransitTrip model = new TransitTrip();

    /**
     * Model tests for TransitTrip
     */
    @Test
    public void testTransitTrip() {
        // TODO: test TransitTrip
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'routeId'
     */
    @Test
    public void routeIdTest() {
        // TODO: test routeId
    }

    /**
     * Test the property 'shapeId'
     */
    @Test
    public void shapeIdTest() {
        // TODO: test shapeId
    }

    /**
     * Test the property 'blockId'
     */
    @Test
    public void blockIdTest() {
        // TODO: test blockId
    }

    /**
     * Test the property 'tripHeadsign'
     */
    @Test
    public void tripHeadsignTest() {
        // TODO: test tripHeadsign
    }

    /**
     * Test the property 'tripShortName'
     */
    @Test
    public void tripShortNameTest() {
        // TODO: test tripShortName
    }

    /**
     * Test the property 'serviceId'
     */
    @Test
    public void serviceIdTest() {
        // TODO: test serviceId
    }

    /**
     * Test the property 'directionId'
     */
    @Test
    public void directionIdTest() {
        // TODO: test directionId
    }

    /**
     * Test the property 'bikesAllowed'
     */
    @Test
    public void bikesAllowedTest() {
        // TODO: test bikesAllowed
    }

    /**
     * Test the property 'wheelchairAccessible'
     */
    @Test
    public void wheelchairAccessibleTest() {
        // TODO: test wheelchairAccessible
    }

}
