/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.TransitScheduleGroup;
import org.openapitools.client.model.TransitScheduleStopTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransitRouteScheduleForDirection
 */
public class TransitRouteScheduleForDirectionTest {
    private final TransitRouteScheduleForDirection model = new TransitRouteScheduleForDirection();

    /**
     * Model tests for TransitRouteScheduleForDirection
     */
    @Test
    public void testTransitRouteScheduleForDirection() {
        // TODO: test TransitRouteScheduleForDirection
    }

    /**
     * Test the property 'directionId'
     */
    @Test
    public void directionIdTest() {
        // TODO: test directionId
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'stopTimes'
     */
    @Test
    public void stopTimesTest() {
        // TODO: test stopTimes
    }

}
