/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EffectType;
import org.openapitools.client.model.TranslatedString;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransitAlertRoute
 */
public class TransitAlertRouteTest {
    private final TransitAlertRoute model = new TransitAlertRoute();

    /**
     * Model tests for TransitAlertRoute
     */
    @Test
    public void testTransitAlertRoute() {
        // TODO: test TransitAlertRoute
    }

    /**
     * Test the property 'routeId'
     */
    @Test
    public void routeIdTest() {
        // TODO: test routeId
    }

    /**
     * Test the property 'stopIds'
     */
    @Test
    public void stopIdsTest() {
        // TODO: test stopIds
    }

    /**
     * Test the property 'header'
     */
    @Test
    public void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'effectType'
     */
    @Test
    public void effectTypeTest() {
        // TODO: test effectType
    }

}
