/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TransitAlertRoute;
import org.openapitools.client.model.TranslatedString;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransitAlert
 */
public class TransitAlertTest {
    private final TransitAlert model = new TransitAlert();

    /**
     * Model tests for TransitAlert
     */
    @Test
    public void testTransitAlert() {
        // TODO: test TransitAlert
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'modifiedTime'
     */
    @Test
    public void modifiedTimeTest() {
        // TODO: test modifiedTime
    }

    /**
     * Test the property 'stopIds'
     */
    @Test
    public void stopIdsTest() {
        // TODO: test stopIds
    }

    /**
     * Test the property 'routeIds'
     */
    @Test
    public void routeIdsTest() {
        // TODO: test routeIds
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'header'
     */
    @Test
    public void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'disableApp'
     */
    @Test
    public void disableAppTest() {
        // TODO: test disableApp
    }

    /**
     * Test the property 'startText'
     */
    @Test
    public void startTextTest() {
        // TODO: test startText
    }

    /**
     * Test the property 'endText'
     */
    @Test
    public void endTextTest() {
        // TODO: test endText
    }

    /**
     * Test the property 'routes'
     */
    @Test
    public void routesTest() {
        // TODO: test routes
    }

}
