/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BikeStreetCategory;
import org.openapitools.client.model.EncodedPolylineBean;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalkStep
 */
public class WalkStepTest {
    private final WalkStep model = new WalkStep();

    /**
     * Model tests for WalkStep
     */
    @Test
    public void testWalkStep() {
        // TODO: test WalkStep
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'relativeDirection'
     */
    @Test
    public void relativeDirectionTest() {
        // TODO: test relativeDirection
    }

    /**
     * Test the property 'streetName'
     */
    @Test
    public void streetNameTest() {
        // TODO: test streetName
    }

    /**
     * Test the property 'absoluteDirection'
     */
    @Test
    public void absoluteDirectionTest() {
        // TODO: test absoluteDirection
    }

    /**
     * Test the property 'stayOn'
     */
    @Test
    public void stayOnTest() {
        // TODO: test stayOn
    }

    /**
     * Test the property 'area'
     */
    @Test
    public void areaTest() {
        // TODO: test area
    }

    /**
     * Test the property 'bogusName'
     */
    @Test
    public void bogusNameTest() {
        // TODO: test bogusName
    }

    /**
     * Test the property 'lon'
     */
    @Test
    public void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'bicycleStreetDirection'
     */
    @Test
    public void bicycleStreetDirectionTest() {
        // TODO: test bicycleStreetDirection
    }

    /**
     * Test the property 'bicycleCategory'
     */
    @Test
    public void bicycleCategoryTest() {
        // TODO: test bicycleCategory
    }

    /**
     * Test the property 'walkingBike'
     */
    @Test
    public void walkingBikeTest() {
        // TODO: test walkingBike
    }

    /**
     * Test the property 'geometry'
     */
    @Test
    public void geometryTest() {
        // TODO: test geometry
    }

}
