/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A láb geometriája.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class EncodedPolylineBean {
  public static final String SERIALIZED_NAME_POINTS = "points";
  @SerializedName(SERIALIZED_NAME_POINTS)
  @javax.annotation.Nullable
  private String points;

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  @javax.annotation.Nullable
  private Integer length;

  public EncodedPolylineBean() {
  }

  public EncodedPolylineBean points(@javax.annotation.Nullable String points) {
    this.points = points;
    return this;
  }

  /**
   * A geometria (polyline) pontjai kódolva.
   * @return points
   */
  @javax.annotation.Nullable
  public String getPoints() {
    return points;
  }

  public void setPoints(@javax.annotation.Nullable String points) {
    this.points = points;
  }


  public EncodedPolylineBean length(@javax.annotation.Nullable Integer length) {
    this.length = length;
    return this;
  }

  /**
   * A geometria (polyline) pontjainak száma.
   * @return length
   */
  @javax.annotation.Nullable
  public Integer getLength() {
    return length;
  }

  public void setLength(@javax.annotation.Nullable Integer length) {
    this.length = length;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EncodedPolylineBean encodedPolylineBean = (EncodedPolylineBean) o;
    return Objects.equals(this.points, encodedPolylineBean.points) &&
        Objects.equals(this.length, encodedPolylineBean.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(points, length);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncodedPolylineBean {\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("points");
    openapiFields.add("length");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EncodedPolylineBean
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EncodedPolylineBean.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EncodedPolylineBean is not found in the empty JSON string", EncodedPolylineBean.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EncodedPolylineBean.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EncodedPolylineBean` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("points") != null && !jsonObj.get("points").isJsonNull()) && !jsonObj.get("points").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `points` to be a primitive type in the JSON string but got `%s`", jsonObj.get("points").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EncodedPolylineBean.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EncodedPolylineBean' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EncodedPolylineBean> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EncodedPolylineBean.class));

       return (TypeAdapter<T>) new TypeAdapter<EncodedPolylineBean>() {
           @Override
           public void write(JsonWriter out, EncodedPolylineBean value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EncodedPolylineBean read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EncodedPolylineBean given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EncodedPolylineBean
   * @throws IOException if the JSON string is invalid with respect to EncodedPolylineBean
   */
  public static EncodedPolylineBean fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EncodedPolylineBean.class);
  }

  /**
   * Convert an instance of EncodedPolylineBean to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

