/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Útitervminták engedélyezése esetén a minták időtartam-adatai.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class PatternStatistics {
  public static final String SERIALIZED_NAME_MIN = "min";
  @SerializedName(SERIALIZED_NAME_MIN)
  @javax.annotation.Nullable
  private Long min;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  @javax.annotation.Nullable
  private Long max;

  public static final String SERIALIZED_NAME_AVG = "avg";
  @SerializedName(SERIALIZED_NAME_AVG)
  @javax.annotation.Nullable
  private Long avg;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public PatternStatistics() {
  }

  public PatternStatistics min(@javax.annotation.Nullable Long min) {
    this.min = min;
    return this;
  }

  /**
   * Minimum érték. Akkor van kitöltve, ha az adatok különbözőek.
   * @return min
   */
  @javax.annotation.Nullable
  public Long getMin() {
    return min;
  }

  public void setMin(@javax.annotation.Nullable Long min) {
    this.min = min;
  }


  public PatternStatistics max(@javax.annotation.Nullable Long max) {
    this.max = max;
    return this;
  }

  /**
   * Maximum érték. Akkor van kitöltve, ha az adatok különbözőek.
   * @return max
   */
  @javax.annotation.Nullable
  public Long getMax() {
    return max;
  }

  public void setMax(@javax.annotation.Nullable Long max) {
    this.max = max;
  }


  public PatternStatistics avg(@javax.annotation.Nullable Long avg) {
    this.avg = avg;
    return this;
  }

  /**
   * Átlag érték. Akkor van kitöltve, ha az adatok megegyeznek.
   * @return avg
   */
  @javax.annotation.Nullable
  public Long getAvg() {
    return avg;
  }

  public void setAvg(@javax.annotation.Nullable Long avg) {
    this.avg = avg;
  }


  public PatternStatistics text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * A klienseken megjelenített szöveg.
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatternStatistics patternStatistics = (PatternStatistics) o;
    return Objects.equals(this.min, patternStatistics.min) &&
        Objects.equals(this.max, patternStatistics.max) &&
        Objects.equals(this.avg, patternStatistics.avg) &&
        Objects.equals(this.text, patternStatistics.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(min, max, avg, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatternStatistics {\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("min");
    openapiFields.add("max");
    openapiFields.add("avg");
    openapiFields.add("text");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PatternStatistics
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PatternStatistics.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PatternStatistics is not found in the empty JSON string", PatternStatistics.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PatternStatistics.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PatternStatistics` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PatternStatistics.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PatternStatistics' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PatternStatistics> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PatternStatistics.class));

       return (TypeAdapter<T>) new TypeAdapter<PatternStatistics>() {
           @Override
           public void write(JsonWriter out, PatternStatistics value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PatternStatistics read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PatternStatistics given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PatternStatistics
   * @throws IOException if the JSON string is invalid with respect to PatternStatistics
   */
  public static PatternStatistics fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PatternStatistics.class);
  }

  /**
   * Convert an instance of PatternStatistics to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

