/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Status;
import org.openapitools.client.model.TransitEntryWithReferencesTransitTicketing;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TicketingMethodResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class TicketingMethodResponse {
  public static final String SERIALIZED_NAME_CURRENT_TIME = "currentTime";
  @SerializedName(SERIALIZED_NAME_CURRENT_TIME)
  @javax.annotation.Nullable
  private Long currentTime;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private Integer version;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Status status;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private Integer code;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private TransitEntryWithReferencesTransitTicketing data;

  public TicketingMethodResponse() {
  }

  public TicketingMethodResponse currentTime(@javax.annotation.Nullable Long currentTime) {
    this.currentTime = currentTime;
    return this;
  }

  /**
   * Az aktuális szerveridő ezredmásodpercben.
   * @return currentTime
   */
  @javax.annotation.Nullable
  public Long getCurrentTime() {
    return currentTime;
  }

  public void setCurrentTime(@javax.annotation.Nullable Long currentTime) {
    this.currentTime = currentTime;
  }


  public TicketingMethodResponse version(@javax.annotation.Nullable Integer version) {
    this.version = version;
    return this;
  }

  /**
   * A válasz API verziója.
   * @return version
   */
  @javax.annotation.Nullable
  public Integer getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable Integer version) {
    this.version = version;
  }


  public TicketingMethodResponse status(@javax.annotation.Nullable Status status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public Status getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Status status) {
    this.status = status;
  }


  public TicketingMethodResponse code(@javax.annotation.Nullable Integer code) {
    this.code = code;
    return this;
  }

  /**
   * A válasz státusz kódja.
   * @return code
   */
  @javax.annotation.Nullable
  public Integer getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable Integer code) {
    this.code = code;
  }


  public TicketingMethodResponse text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * A válasz szövege.
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public TicketingMethodResponse data(@javax.annotation.Nullable TransitEntryWithReferencesTransitTicketing data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  public TransitEntryWithReferencesTransitTicketing getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable TransitEntryWithReferencesTransitTicketing data) {
    this.data = data;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketingMethodResponse ticketingMethodResponse = (TicketingMethodResponse) o;
    return Objects.equals(this.currentTime, ticketingMethodResponse.currentTime) &&
        Objects.equals(this.version, ticketingMethodResponse.version) &&
        Objects.equals(this.status, ticketingMethodResponse.status) &&
        Objects.equals(this.code, ticketingMethodResponse.code) &&
        Objects.equals(this.text, ticketingMethodResponse.text) &&
        Objects.equals(this.data, ticketingMethodResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentTime, version, status, code, text, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketingMethodResponse {\n");
    sb.append("    currentTime: ").append(toIndentedString(currentTime)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("currentTime");
    openapiFields.add("version");
    openapiFields.add("status");
    openapiFields.add("code");
    openapiFields.add("text");
    openapiFields.add("data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TicketingMethodResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TicketingMethodResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TicketingMethodResponse is not found in the empty JSON string", TicketingMethodResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TicketingMethodResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TicketingMethodResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        Status.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      // validate the optional field `data`
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        TransitEntryWithReferencesTransitTicketing.validateJsonElement(jsonObj.get("data"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TicketingMethodResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TicketingMethodResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TicketingMethodResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TicketingMethodResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TicketingMethodResponse>() {
           @Override
           public void write(JsonWriter out, TicketingMethodResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TicketingMethodResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TicketingMethodResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TicketingMethodResponse
   * @throws IOException if the JSON string is invalid with respect to TicketingMethodResponse
   */
  public static TicketingMethodResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TicketingMethodResponse.class);
  }

  /**
   * Convert an instance of TicketingMethodResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

