/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A zavar végének időpontjához tartozó szöveg.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class TranslatedString {
  public static final String SERIALIZED_NAME_TRANSLATIONS = "translations";
  @SerializedName(SERIALIZED_NAME_TRANSLATIONS)
  @javax.annotation.Nullable
  private Map<String, String> translations = new HashMap<>();

  public static final String SERIALIZED_NAME_SOME_TRANSLATION = "someTranslation";
  @SerializedName(SERIALIZED_NAME_SOME_TRANSLATION)
  @javax.annotation.Nullable
  private String someTranslation;

  public TranslatedString() {
  }

  public TranslatedString translations(@javax.annotation.Nullable Map<String, String> translations) {
    this.translations = translations;
    return this;
  }

  public TranslatedString putTranslationsItem(String key, String translationsItem) {
    if (this.translations == null) {
      this.translations = new HashMap<>();
    }
    this.translations.put(key, translationsItem);
    return this;
  }

  /**
   * Lokalizáció és a hozzá tartozó fordítások összerendelése.
   * @return translations
   */
  @javax.annotation.Nullable
  public Map<String, String> getTranslations() {
    return translations;
  }

  public void setTranslations(@javax.annotation.Nullable Map<String, String> translations) {
    this.translations = translations;
  }


  public TranslatedString someTranslation(@javax.annotation.Nullable String someTranslation) {
    this.someTranslation = someTranslation;
    return this;
  }

  /**
   * A fordítás-összerendelések első eleme.
   * @return someTranslation
   */
  @javax.annotation.Nullable
  public String getSomeTranslation() {
    return someTranslation;
  }

  public void setSomeTranslation(@javax.annotation.Nullable String someTranslation) {
    this.someTranslation = someTranslation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslatedString translatedString = (TranslatedString) o;
    return Objects.equals(this.translations, translatedString.translations) &&
        Objects.equals(this.someTranslation, translatedString.someTranslation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(translations, someTranslation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslatedString {\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    someTranslation: ").append(toIndentedString(someTranslation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("translations");
    openapiFields.add("someTranslation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TranslatedString
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TranslatedString.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TranslatedString is not found in the empty JSON string", TranslatedString.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TranslatedString.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TranslatedString` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("someTranslation") != null && !jsonObj.get("someTranslation").isJsonNull()) && !jsonObj.get("someTranslation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `someTranslation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("someTranslation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TranslatedString.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TranslatedString' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TranslatedString> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TranslatedString.class));

       return (TypeAdapter<T>) new TypeAdapter<TranslatedString>() {
           @Override
           public void write(JsonWriter out, TranslatedString value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TranslatedString read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TranslatedString given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TranslatedString
   * @throws IOException if the JSON string is invalid with respect to TranslatedString
   */
  public static TranslatedString fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TranslatedString.class);
  }

  /**
   * Convert an instance of TranslatedString to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

