/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TransitScheduleStopTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A lekért adat.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class TransitArrivalsAndDepartures {
  public static final String SERIALIZED_NAME_STOP_ID = "stopId";
  @SerializedName(SERIALIZED_NAME_STOP_ID)
  @javax.annotation.Nullable
  private String stopId;

  public static final String SERIALIZED_NAME_ROUTE_IDS = "routeIds";
  @SerializedName(SERIALIZED_NAME_ROUTE_IDS)
  @javax.annotation.Nullable
  private List<String> routeIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_ALERT_IDS = "alertIds";
  @SerializedName(SERIALIZED_NAME_ALERT_IDS)
  @javax.annotation.Nullable
  private List<String> alertIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEARBY_STOP_IDS = "nearbyStopIds";
  @SerializedName(SERIALIZED_NAME_NEARBY_STOP_IDS)
  @javax.annotation.Nullable
  private List<String> nearbyStopIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_STOP_TIMES = "stopTimes";
  @SerializedName(SERIALIZED_NAME_STOP_TIMES)
  @javax.annotation.Nullable
  private List<TransitScheduleStopTime> stopTimes = new ArrayList<>();

  public TransitArrivalsAndDepartures() {
  }

  public TransitArrivalsAndDepartures stopId(@javax.annotation.Nullable String stopId) {
    this.stopId = stopId;
    return this;
  }

  /**
   * A megálló azonosítója.
   * @return stopId
   */
  @javax.annotation.Nullable
  public String getStopId() {
    return stopId;
  }

  public void setStopId(@javax.annotation.Nullable String stopId) {
    this.stopId = stopId;
  }


  public TransitArrivalsAndDepartures routeIds(@javax.annotation.Nullable List<String> routeIds) {
    this.routeIds = routeIds;
    return this;
  }

  public TransitArrivalsAndDepartures addRouteIdsItem(String routeIdsItem) {
    if (this.routeIds == null) {
      this.routeIds = new ArrayList<>();
    }
    this.routeIds.add(routeIdsItem);
    return this;
  }

  /**
   * A megállóhoz tartozó járatok azonosítói.
   * @return routeIds
   */
  @javax.annotation.Nullable
  public List<String> getRouteIds() {
    return routeIds;
  }

  public void setRouteIds(@javax.annotation.Nullable List<String> routeIds) {
    this.routeIds = routeIds;
  }


  public TransitArrivalsAndDepartures alertIds(@javax.annotation.Nullable List<String> alertIds) {
    this.alertIds = alertIds;
    return this;
  }

  public TransitArrivalsAndDepartures addAlertIdsItem(String alertIdsItem) {
    if (this.alertIds == null) {
      this.alertIds = new ArrayList<>();
    }
    this.alertIds.add(alertIdsItem);
    return this;
  }

  /**
   * A megállóhoz tartozó aktív zavarok.
   * @return alertIds
   */
  @javax.annotation.Nullable
  public List<String> getAlertIds() {
    return alertIds;
  }

  public void setAlertIds(@javax.annotation.Nullable List<String> alertIds) {
    this.alertIds = alertIds;
  }


  public TransitArrivalsAndDepartures nearbyStopIds(@javax.annotation.Nullable List<String> nearbyStopIds) {
    this.nearbyStopIds = nearbyStopIds;
    return this;
  }

  public TransitArrivalsAndDepartures addNearbyStopIdsItem(String nearbyStopIdsItem) {
    if (this.nearbyStopIds == null) {
      this.nearbyStopIds = new ArrayList<>();
    }
    this.nearbyStopIds.add(nearbyStopIdsItem);
    return this;
  }

  /**
   * A közeli megállók azonosítói.
   * @return nearbyStopIds
   */
  @javax.annotation.Nullable
  public List<String> getNearbyStopIds() {
    return nearbyStopIds;
  }

  public void setNearbyStopIds(@javax.annotation.Nullable List<String> nearbyStopIds) {
    this.nearbyStopIds = nearbyStopIds;
  }


  public TransitArrivalsAndDepartures stopTimes(@javax.annotation.Nullable List<TransitScheduleStopTime> stopTimes) {
    this.stopTimes = stopTimes;
    return this;
  }

  public TransitArrivalsAndDepartures addStopTimesItem(TransitScheduleStopTime stopTimesItem) {
    if (this.stopTimes == null) {
      this.stopTimes = new ArrayList<>();
    }
    this.stopTimes.add(stopTimesItem);
    return this;
  }

  /**
   * A megállóhoz tartozó menetrendi bejegyzések.
   * @return stopTimes
   */
  @javax.annotation.Nullable
  public List<TransitScheduleStopTime> getStopTimes() {
    return stopTimes;
  }

  public void setStopTimes(@javax.annotation.Nullable List<TransitScheduleStopTime> stopTimes) {
    this.stopTimes = stopTimes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransitArrivalsAndDepartures transitArrivalsAndDepartures = (TransitArrivalsAndDepartures) o;
    return Objects.equals(this.stopId, transitArrivalsAndDepartures.stopId) &&
        Objects.equals(this.routeIds, transitArrivalsAndDepartures.routeIds) &&
        Objects.equals(this.alertIds, transitArrivalsAndDepartures.alertIds) &&
        Objects.equals(this.nearbyStopIds, transitArrivalsAndDepartures.nearbyStopIds) &&
        Objects.equals(this.stopTimes, transitArrivalsAndDepartures.stopTimes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopId, routeIds, alertIds, nearbyStopIds, stopTimes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransitArrivalsAndDepartures {\n");
    sb.append("    stopId: ").append(toIndentedString(stopId)).append("\n");
    sb.append("    routeIds: ").append(toIndentedString(routeIds)).append("\n");
    sb.append("    alertIds: ").append(toIndentedString(alertIds)).append("\n");
    sb.append("    nearbyStopIds: ").append(toIndentedString(nearbyStopIds)).append("\n");
    sb.append("    stopTimes: ").append(toIndentedString(stopTimes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("stopId");
    openapiFields.add("routeIds");
    openapiFields.add("alertIds");
    openapiFields.add("nearbyStopIds");
    openapiFields.add("stopTimes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransitArrivalsAndDepartures
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    /*
    if (jsonElement == null) {
        if (!TransitArrivalsAndDepartures.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransitArrivalsAndDepartures is not found in the empty JSON string", TransitArrivalsAndDepartures.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransitArrivalsAndDepartures.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TransitArrivalsAndDepartures` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("stopId") != null && !jsonObj.get("stopId").isJsonNull()) && !jsonObj.get("stopId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stopId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stopId").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("routeIds") != null && !jsonObj.get("routeIds").isJsonNull() && !jsonObj.get("routeIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `routeIds` to be an array in the JSON string but got `%s`", jsonObj.get("routeIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("alertIds") != null && !jsonObj.get("alertIds").isJsonNull() && !jsonObj.get("alertIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `alertIds` to be an array in the JSON string but got `%s`", jsonObj.get("alertIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("nearbyStopIds") != null && !jsonObj.get("nearbyStopIds").isJsonNull() && !jsonObj.get("nearbyStopIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `nearbyStopIds` to be an array in the JSON string but got `%s`", jsonObj.get("nearbyStopIds").toString()));
      }
      if (jsonObj.get("stopTimes") != null && !jsonObj.get("stopTimes").isJsonNull()) {
        JsonArray jsonArraystopTimes = jsonObj.getAsJsonArray("stopTimes");
        if (jsonArraystopTimes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("stopTimes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `stopTimes` to be an array in the JSON string but got `%s`", jsonObj.get("stopTimes").toString()));
          }

          // validate the optional field `stopTimes` (array)
          for (int i = 0; i < jsonArraystopTimes.size(); i++) {
            TransitScheduleStopTime.validateJsonElement(jsonArraystopTimes.get(i));
          };
        }
      }*/
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransitArrivalsAndDepartures.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransitArrivalsAndDepartures' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransitArrivalsAndDepartures> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransitArrivalsAndDepartures.class));

       return (TypeAdapter<T>) new TypeAdapter<TransitArrivalsAndDepartures>() {
           @Override
           public void write(JsonWriter out, TransitArrivalsAndDepartures value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransitArrivalsAndDepartures read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransitArrivalsAndDepartures given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransitArrivalsAndDepartures
   * @throws IOException if the JSON string is invalid with respect to TransitArrivalsAndDepartures
   */
  public static TransitArrivalsAndDepartures fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransitArrivalsAndDepartures.class);
  }

  /**
   * Convert an instance of TransitArrivalsAndDepartures to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

