/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MobileTransitReferences;
import org.openapitools.client.model.OTPTransitReferences;
import org.openapitools.client.model.TransitAgency;
import org.openapitools.client.model.TransitAlert;
import org.openapitools.client.model.TransitRoute;
import org.openapitools.client.model.TransitStop;
import org.openapitools.client.model.TransitTrip;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class TransitReferences extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TransitReferences.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TransitReferences.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TransitReferences' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<OTPTransitReferences> adapterOTPTransitReferences = gson.getDelegateAdapter(this, TypeToken.get(OTPTransitReferences.class));
            final TypeAdapter<MobileTransitReferences> adapterMobileTransitReferences = gson.getDelegateAdapter(this, TypeToken.get(MobileTransitReferences.class));

            return (TypeAdapter<T>) new TypeAdapter<TransitReferences>() {
                @Override
                public void write(JsonWriter out, TransitReferences value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `OTPTransitReferences`
                    if (value.getActualInstance() instanceof OTPTransitReferences) {
                        JsonElement element = adapterOTPTransitReferences.toJsonTree((OTPTransitReferences)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `MobileTransitReferences`
                    if (value.getActualInstance() instanceof MobileTransitReferences) {
                        JsonElement element = adapterMobileTransitReferences.toJsonTree((MobileTransitReferences)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: MobileTransitReferences, OTPTransitReferences");
                }

                @Override
                public TransitReferences read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize OTPTransitReferences
                    try {
                        // validate the JSON object to see if any exception is thrown
                        OTPTransitReferences.validateJsonElement(jsonElement);
                        actualAdapter = adapterOTPTransitReferences;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'OTPTransitReferences'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for OTPTransitReferences failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'OTPTransitReferences'", e);
                    }
                    // deserialize MobileTransitReferences
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MobileTransitReferences.validateJsonElement(jsonElement);
                        actualAdapter = adapterMobileTransitReferences;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'MobileTransitReferences'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for MobileTransitReferences failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MobileTransitReferences'", e);
                    }

                    if (match == 1) {
                        TransitReferences ret = new TransitReferences();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for TransitReferences: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TransitReferences() {
        super("oneOf", Boolean.FALSE);
    }

    public TransitReferences(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("OTPTransitReferences", OTPTransitReferences.class);
        schemas.put("MobileTransitReferences", MobileTransitReferences.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TransitReferences.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * MobileTransitReferences, OTPTransitReferences
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof OTPTransitReferences) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof MobileTransitReferences) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be MobileTransitReferences, OTPTransitReferences");
    }

    /**
     * Get the actual instance, which can be the following:
     * MobileTransitReferences, OTPTransitReferences
     *
     * @return The actual instance (MobileTransitReferences, OTPTransitReferences)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `OTPTransitReferences`. If the actual instance is not `OTPTransitReferences`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OTPTransitReferences`
     * @throws ClassCastException if the instance is not `OTPTransitReferences`
     */
    public OTPTransitReferences getOTPTransitReferences() throws ClassCastException {
        return (OTPTransitReferences)super.getActualInstance();
    }

    /**
     * Get the actual instance of `MobileTransitReferences`. If the actual instance is not `MobileTransitReferences`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MobileTransitReferences`
     * @throws ClassCastException if the instance is not `MobileTransitReferences`
     */
    public MobileTransitReferences getMobileTransitReferences() throws ClassCastException {
        return (MobileTransitReferences)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TransitReferences
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with OTPTransitReferences
        try {
            OTPTransitReferences.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for OTPTransitReferences failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with MobileTransitReferences
        try {
            MobileTransitReferences.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for MobileTransitReferences failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for TransitReferences with oneOf schemas: MobileTransitReferences, OTPTransitReferences. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of TransitReferences given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TransitReferences
     * @throws IOException if the JSON string is invalid with respect to TransitReferences
     */
    public static TransitReferences fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TransitReferences.class);
    }

    /**
     * Convert an instance of TransitReferences to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

