/*
 * realCity Query Server API
 * Specification for the realCity Query Server API.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TicketingLocation;
import org.openapitools.client.model.TicketingProduct;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A lekért adat.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-15T15:47:41.658152+02:00[Europe/Budapest]", comments = "Generator version: 7.12.0")
public class TransitTicketing {
  public static final String SERIALIZED_NAME_LAST_MODIFIED_TIME = "lastModifiedTime";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_TIME)
  @javax.annotation.Nullable
  private Long lastModifiedTime;

  public static final String SERIALIZED_NAME_OLDEST_MODIFIED_TIME = "oldestModifiedTime";
  @SerializedName(SERIALIZED_NAME_OLDEST_MODIFIED_TIME)
  @javax.annotation.Nullable
  private Long oldestModifiedTime;

  public static final String SERIALIZED_NAME_LOCATIONS = "locations";
  @SerializedName(SERIALIZED_NAME_LOCATIONS)
  @javax.annotation.Nullable
  private List<TicketingLocation> locations = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  @javax.annotation.Nullable
  private List<TicketingProduct> products = new ArrayList<>();

  public TransitTicketing() {
  }

  public TransitTicketing lastModifiedTime(@javax.annotation.Nullable Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

  /**
   * A jegyértékesítési adatok legutóbbi módosulásának időpontja.
   * @return lastModifiedTime
   */
  @javax.annotation.Nullable
  public Long getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(@javax.annotation.Nullable Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }


  public TransitTicketing oldestModifiedTime(@javax.annotation.Nullable Long oldestModifiedTime) {
    this.oldestModifiedTime = oldestModifiedTime;
    return this;
  }

  /**
   * A legrégebb óta módosított értékesítési hely vagy termék módosításának időpontja.
   * @return oldestModifiedTime
   */
  @javax.annotation.Nullable
  public Long getOldestModifiedTime() {
    return oldestModifiedTime;
  }

  public void setOldestModifiedTime(@javax.annotation.Nullable Long oldestModifiedTime) {
    this.oldestModifiedTime = oldestModifiedTime;
  }


  public TransitTicketing locations(@javax.annotation.Nullable List<TicketingLocation> locations) {
    this.locations = locations;
    return this;
  }

  public TransitTicketing addLocationsItem(TicketingLocation locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

  /**
   * A jegyértékesítési pontok listája.
   * @return locations
   */
  @javax.annotation.Nullable
  public List<TicketingLocation> getLocations() {
    return locations;
  }

  public void setLocations(@javax.annotation.Nullable List<TicketingLocation> locations) {
    this.locations = locations;
  }


  public TransitTicketing products(@javax.annotation.Nullable List<TicketingProduct> products) {
    this.products = products;
    return this;
  }

  public TransitTicketing addProductsItem(TicketingProduct productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

  /**
   * A termékek listája.
   * @return products
   */
  @javax.annotation.Nullable
  public List<TicketingProduct> getProducts() {
    return products;
  }

  public void setProducts(@javax.annotation.Nullable List<TicketingProduct> products) {
    this.products = products;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransitTicketing transitTicketing = (TransitTicketing) o;
    return Objects.equals(this.lastModifiedTime, transitTicketing.lastModifiedTime) &&
        Objects.equals(this.oldestModifiedTime, transitTicketing.oldestModifiedTime) &&
        Objects.equals(this.locations, transitTicketing.locations) &&
        Objects.equals(this.products, transitTicketing.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastModifiedTime, oldestModifiedTime, locations, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransitTicketing {\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("    oldestModifiedTime: ").append(toIndentedString(oldestModifiedTime)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lastModifiedTime");
    openapiFields.add("oldestModifiedTime");
    openapiFields.add("locations");
    openapiFields.add("products");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransitTicketing
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransitTicketing.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransitTicketing is not found in the empty JSON string", TransitTicketing.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransitTicketing.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TransitTicketing` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("locations") != null && !jsonObj.get("locations").isJsonNull()) {
        JsonArray jsonArraylocations = jsonObj.getAsJsonArray("locations");
        if (jsonArraylocations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("locations").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `locations` to be an array in the JSON string but got `%s`", jsonObj.get("locations").toString()));
          }

          // validate the optional field `locations` (array)
          for (int i = 0; i < jsonArraylocations.size(); i++) {
            TicketingLocation.validateJsonElement(jsonArraylocations.get(i));
          };
        }
      }
      if (jsonObj.get("products") != null && !jsonObj.get("products").isJsonNull()) {
        JsonArray jsonArrayproducts = jsonObj.getAsJsonArray("products");
        if (jsonArrayproducts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("products").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `products` to be an array in the JSON string but got `%s`", jsonObj.get("products").toString()));
          }

          // validate the optional field `products` (array)
          for (int i = 0; i < jsonArrayproducts.size(); i++) {
            TicketingProduct.validateJsonElement(jsonArrayproducts.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransitTicketing.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransitTicketing' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransitTicketing> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransitTicketing.class));

       return (TypeAdapter<T>) new TypeAdapter<TransitTicketing>() {
           @Override
           public void write(JsonWriter out, TransitTicketing value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransitTicketing read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransitTicketing given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransitTicketing
   * @throws IOException if the JSON string is invalid with respect to TransitTicketing
   */
  public static TransitTicketing fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransitTicketing.class);
  }

  /**
   * Convert an instance of TransitTicketing to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

